version: "3"
services:
  automation-webapp:
    build:
      dockerfile: Dockerfile-tomcat
      context: ./
    image: custom-tomcat8
    container_name: automation-webapp
    ports:
     - 8080:8080
    environment:
      CATALINA_OPTS: >-
        -DappUrl=http://automation-webapp:8080
    volumes:
     - ./tomcat-conf:/usr/local/tomcat/conf
     - ./webapps:/usr/local/tomcat/webapps
     - ${MOUNTED_DIR}/nfs:/nfs
     - ${MOUNTED_DIR}/log:/var/log/msb
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
networks:
  default:
    external:
      name: msb-automation-network
