version: '3'
services:
  msb-database:
    image: 192.168.20.37:9002/mysql/mysql-server:5.7.26
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: msb
      MYSQL_PASSWORD: msb
      MYSQL_DATABASE: msb
    ports:
    - 3306:3306
    volumes:
     - /opt/dockervol:/var/lib/mysql
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
networks:
  default:
    external:
      name: msb-automation-network
