version: '3.7'
services:
  selenium-hub:
    image: 192.168.20.37:9002/selenium/hub:3.141.59-xenon
    container_name: selenium-hub
    environment:
    - GRID_TIMEOUT=300
    ports:
    - 4444:4444
networks:
  default:
    external:
      name: msb-automation-network
